### ISSUE TITLE
javaldx: Could not find a Java Runtime Environment!

### ISSUE THREAD

**Issue by joachimvandenabeele** [shelfio/libreoffice-lambda-base-image#6]
Hi,

I created the docker image and lambda function based on the documentation, but when calling the convertTo command I always get "javaldx: Could not find a Java Runtime Environment!". I have checked the installed version of @shelf/aws-lambda-libreoffice and this is 4.0.4. I have used the base image: public.ecr.aws/shelf/lambda-libreoffice-base:7.3-node16-x86_64 and I set HOME to /tmp as described. Am I doing something wrong?

Kind regards

**Comment by sam2k13** [comment]
Same issue for me as well

**Comment by vladgolubev** [comment]
Ignore this error. I see it as well, but the Libreoffice still works fine even w/o it

**Comment by joachimvandenabeele** [comment]
> Ignore this error. I see it as well, but the Libreoffice still works fine even w/ this error

Ok, I'll check today and close if it is the case. Thank you for replying.

Kind regards

**Comment by Shivamkumar285** [comment]
Hey ! Im also facing the same issue. Any fix for that @joachimvandenabeele @vladgolubev @sam2k13

**Comment by joachimvandenabeele** [comment]
> Hey ! Im also facing the same issue. Any fix for that @joachimvandenabeele @vladgolubev @sam2k13

Hi @Shivamkumar285,
As @vladgolubev commented, it still worked fine for me even with this error.

Kind regards

**Comment by ale-ctc** [comment]
I know this is closed but I cannot convert to pdf with this error.
