### ISSUE TITLE
LibreOffice 7.4 version image

### ISSUE THREAD

**Issue by bjalt** [shelfio/libreoffice-lambda-base-image#8]
With the version 7.4 of LibreOffice one can specify filters for pdf export.

See https://vmiklos.hu/blog/pdf-convert-to.html for details.

**Comment by vladgolubev** [comment]
PRs are welcome ;)

It should be just a matter of updating the version in the Dockerfile

https://github.com/shelfio/libreoffice-lambda-base-image/blob/master/Dockerfile.node16-x86_64#L16-L22

Otherwise, if @bjalt doesn't create a PR soon, @BodyaFlesh please take a look at it once you get there.

**Comment by bjalt** [comment]
To use this in the lambdas we also need to upgrade https://github.com/shelfio/aws-lambda-libreoffice/blob/d74f0e2dfbdbd5f088673944982eb0c5fc5f3af0/src/convert.ts#L14
